#!/usr/bin/env python3
"""
GUI viewer for heatshrink-compressed GIF sprites.

Reads C header files generated by gif2h.py and displays the animations
magnified, alongside the source GIF for visual comparison.

Usage:
    python3 view_sprites.py                     # Show all GIF headers in GIF/
    python3 view_sprites.py GIF/owl.h GIF/fire.h  # Show specific headers

Keyboard shortcuts:
    Space: Play/Pause
    Left/Right: Previous/Next animation
    PgUp/PgDn or Ctrl+Left/Right: Previous/Next frame
    +/- or Mouse Wheel: Zoom in/out
    1-9: Select animation (if multiple loaded)
"""

import sys
import os
import re
import glob
import argparse
from pathlib import Path
from PIL import Image

from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QPushButton, QSlider, QComboBox, QGroupBox, QSpinBox,
    QFileDialog, QSplitter, QFrame, QGridLayout, QScrollArea,
    QProgressBar, QSizePolicy
)
from PyQt6.QtCore import Qt, QTimer, QSize, pyqtSignal, QEvent, QPoint
from PyQt6.QtGui import QPixmap, QImage, QPainter, QColor, QFont, QWheelEvent, QBrush, QPen, QKeySequence, QShortcut
from PyQt6.QtWidgets import QStyleOption
from typing import cast
from PyQt6.QtWidgets import QWidget as QWidgetType

# Add heatshrink_python to path
_sys_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'heatshrink_python')
if _sys_path not in sys.path:
    sys.path.insert(0, _sys_path)

from heatshrink_decoder import decompress


def parse_header_file(filepath):
    """Parse a C header file and extract sprite metadata and compressed data."""
    with open(filepath, 'r') as f:
        content = f.read()

    result = {
        'filename': os.path.basename(filepath),
        'path': filepath,
        'comments': [],
        'datasize': 0,
        'frames': 0,
        'duration': 100,
        'flags': 0,
        'palette_entries': 0,
        'compressed_data': b''
    }

    # Extract comments
    comment_pattern = r'^//(.+)$'
    for line in content.split('\n'):
        match = re.match(comment_pattern, line.strip())
        if match:
            result['comments'].append(match.group(1).strip())

    # Extract struct fields
    datasize_match = re.search(r'uint16_t datasize\s*=\s*(\d+);', content)
    if datasize_match:
        result['datasize'] = int(datasize_match.group(1))

    frames_match = re.search(r'uint16_t frames\s*=\s*(\d+);', content)
    if frames_match:
        result['frames'] = int(frames_match.group(1))

    duration_match = re.search(r'uint16_t duration\s*=\s*(\d+);', content)
    if duration_match:
        result['duration'] = int(duration_match.group(1))

    flags_match = re.search(r'uint8_t flags\s*=\s*(\d+);', content)
    if flags_match:
        result['flags'] = int(flags_match.group(1))

    palette_match = re.search(r'uint8_t palette_entries\s*=\s*(\d+);', content)
    if palette_match:
        result['palette_entries'] = int(palette_match.group(1))

    # Extract compressed data bytes
    hs_data_match = re.search(
        r'uint8_t\s+hs_data\[\d+\]\s*=\s*\{([^}]+)\}',
        content,
        re.DOTALL
    )
    if hs_data_match:
        hex_str = hs_data_match.group(1)
        hex_bytes = re.findall(r'0x([0-9a-fA-F]{2})', hex_str)
        result['compressed_data'] = bytes(int(b, 16) for b in hex_bytes)

    return result


def decompress_sprite(header_data):
    """Decompress sprite data and return palette + frames."""
    compressed = header_data['compressed_data']
    if not compressed:
        return None, []

    try:
        decompressed = decompress(compressed, 8, 7)
    except Exception as e:
        print(f'[decompress_sprite] Failed to decompress {header_data["filename"]}: {e}')
        return None, []

    # First bytes are palette (RGB triplets)
    palette_entries = header_data['palette_entries']
    palette_size = palette_entries * 3

    if len(decompressed) < palette_size:
        return None, []

    palette = []
    for i in range(palette_entries):
        r = decompressed[i * 3]
        g = decompressed[i * 3 + 1]
        b = decompressed[i * 3 + 2]
        palette.append((r, g, b))

    # Remaining bytes are pixel data (one byte per pixel per frame)
    pixel_data = decompressed[palette_size:]
    pixels_per_frame = 16 * 16  # 256 pixels for 16x16

    frames = []
    for frame_idx in range(header_data['frames']):
        start = frame_idx * pixels_per_frame
        end = start + pixels_per_frame
        if end <= len(pixel_data):
            frames.append(pixel_data[start:end])

    return palette, frames


def pixels_to_image(pixels, palette, size, transform_mode):
    """Convert pixel indices and palette to a QPixmap with specified scaling.
    
    Transparent pixels (palette index 0) are rendered as fully transparent,
    allowing the cross-hatch background to show through.
    """
    img = QImage(16, 16, QImage.Format.Format_ARGB32)

    # Fill with transparent background
    img.fill(Qt.GlobalColor.transparent)

    # Draw pixels
    for y in range(16):
        for x in range(16):
            idx = y * 16 + x
            if idx >= len(pixels):
                continue
            
            pixel_idx = pixels[idx]
            
            if pixel_idx != 0:
                # Solid pixel - use palette color
                r, g, b = palette[pixel_idx]
                img.setPixel(x, y, QColor(r, g, b).rgb())

    # Scale up with specified transform mode
    scaled = img.scaled(
        size, size,
        Qt.AspectRatioMode.KeepAspectRatio,
        transform_mode
    )

    return QPixmap.fromImage(scaled)


# Mapping from string to Qt transform mode
TRANSFORM_MODES = {
    'Nearest Neighbor': Qt.TransformationMode.FastTransformation,
    'Bicubic': Qt.TransformationMode.SmoothTransformation,
}


class BackgroundWidget(QWidget):
    """Animated grid of squares rotated 45 degrees on black background.
    
    Grey lines on black background, slowly panning in x and y.
    """
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setAttribute(Qt.WidgetAttribute.WA_TransparentForMouseEvents)
        self.setAttribute(Qt.WidgetAttribute.WA_NoSystemBackground)
        self.offset_x = 0.0
        self.offset_y = 0.0
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.animate)
        self.timer.start(33)  # ~30 fps for smooth animation
        
    def animate(self):
        self.offset_x += 0.5
        self.offset_y += 0.5
        # Wrap at pattern period to avoid floating point issues
        # Pattern repeats when offset changes by step (perpendicular spacing)
        period = 16 * 16  # full cycle before floating point drift
        if self.offset_x >= period:
            self.offset_x -= period
        if self.offset_y >= period:
            self.offset_y -= period
        self.update()
        
    def resizeEvent(self, event):
        super().resizeEvent(event)
        self.update()
        
    def paintEvent(self, event):
        painter = QPainter(self)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)
        
        # Black background
        painter.fillRect(self.rect(), QColor(0, 0, 0))
        
        # Grid of squares rotated 45 degrees
        # Lines at 45°: x - y = c
        # Lines at 135°: x + y = c
        # Perpendicular spacing between parallel lines = 16px
        # So c values are spaced by 16 * sqrt(2)
        import math
        step = 16 * math.sqrt(2)
        
        # Darker grey, wider pen
        pen = QPen(QColor(80, 80, 80), 1.75)
        painter.setPen(pen)
        
        w = self.width()
        h = self.height()
        
        # Calculate the effective c offset for each line family
        c45_offset = self.offset_x - self.offset_y
        c135_offset = self.offset_x + self.offset_y
        
        # Range of c values to cover the widget with generous margin
        # Need extra margin to ensure lines at edges are drawn
        diag = math.sqrt(w * w + h * h)
        margin = diag / step + 2
        
        min_c = -diag / step - margin
        max_c = diag / step + margin
        
        # Draw 45° lines: x - y = c_int * step + c45_offset
        c_start = math.floor(min_c)
        c_end = math.ceil(max_c)
        
        for c_int in range(c_start, c_end + 1):
            c = c_int * step + c45_offset
            
            # Find intersections with widget bounds [0,w] x [0,h]
            # For 45° lines (direction (1,1)), order by increasing x+y
            candidates = []
            # Top edge: y=0, x=c
            if 0 <= c <= w:
                candidates.append((c, 0.0))
            # Bottom edge: y=h, x=c+h
            if 0 <= c + h <= w:
                candidates.append((c + h, float(h)))
            # Left edge: x=0, y=-c
            if 0 <= -c <= h:
                candidates.append((0.0, -c))
            # Right edge: x=w, y=w-c
            if 0 <= w - c <= h:
                candidates.append((float(w), w - c))
            
            if len(candidates) >= 2:
                # Sort by x coordinate (for 45° lines, x increases along the line)
                candidates.sort(key=lambda p: p[0])
                painter.drawLine(
                    int(round(candidates[0][0])), int(round(candidates[0][1])),
                    int(round(candidates[-1][0])), int(round(candidates[-1][1])))
        
        # Draw 135° lines: x + y = c_int * step + c135_offset
        for c_int in range(c_start, c_end + 1):
            c = c_int * step + c135_offset
            
            # Find intersections with widget bounds [0,w] x [0,h]
            # For 135° lines (direction (-1,1)), order by increasing x
            candidates = []
            # Top edge: y=0, x=c
            if 0 <= c <= w:
                candidates.append((c, 0.0))
            # Bottom edge: y=h, x=c-h
            if 0 <= c - h <= w:
                candidates.append((c - h, float(h)))
            # Left edge: x=0, y=c
            if 0 <= c <= h:
                candidates.append((0.0, c))
            # Right edge: x=w, y=c-w
            if 0 <= c - w <= h:
                candidates.append((float(w), c - w))
            
            if len(candidates) >= 2:
                # Sort by x coordinate (for 135° lines, x decreases along the line)
                candidates.sort(key=lambda p: p[0])
                painter.drawLine(
                    int(round(candidates[0][0])), int(round(candidates[0][1])),
                    int(round(candidates[-1][0])), int(round(candidates[-1][1])))
        
        painter.end()


class SpriteViewer(QMainWindow):
    """Main window for viewing heatshrink-compressed sprite animations."""

    def __init__(self, header_files=None):
        super().__init__()
        self.sprites = []
        self.current_sprite_idx = 0
        self.current_frame = 0
        self.playing = True  # Auto-play by default
        self.magnification = 24
        self.fps = 10
        self.transform_mode = Qt.TransformationMode.FastTransformation  # Matches default combo selection
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.next_frame)
        # Cached decompressed data (avoids re-decompressing on every frame/scale change)
        self._cached_palette = None
        self._cached_frames = None

        self.init_ui()

        # Load sprites
        if header_files:
            files = header_files
        else:
            files = sorted(glob.glob('GIF/*.h'))

        for f in files:
            if os.path.exists(f):
                header = parse_header_file(f)
                if header['compressed_data']:
                    self.sprites.append(header)

        if self.sprites:
            self.load_sprite(0)
            # Start auto-play
            self.playing = True
            self.play_btn.setText('Pause')
            self.timer.start(int(1000 / self.fps))
        else:
            self.statusBar().showMessage('No sprite headers found. Add GIF/*.h files.')
        
        # Size window to fit max zoom (30x) with visible background border
        # At 30x: panels = 480px each, gap = 240px, total content = 1200px wide
        # Add ~100px border on each side for visible background
        self.resize(1320, 890)

    def init_ui(self):
        """Initialize the user interface."""
        self.setWindowTitle('Heatshrink Sprite Viewer')
        self.setMinimumSize(1200, 800)

        # Central widget
        central = QWidget()
        self.setCentralWidget(central)
        main_layout = QVBoxLayout(central)
        main_layout.setContentsMargins(0, 0, 0, 0)
        main_layout.setSpacing(0)

        # Top bar: sprite selector and controls
        top_layout = QHBoxLayout()

        # Sprite selector
        sprite_group = QGroupBox('Sprites')
        sprite_layout = QVBoxLayout()

        self.sprite_combo = QComboBox()
        self.sprite_combo.currentIndexChanged.connect(self.sprite_changed)
        sprite_layout.addWidget(self.sprite_combo)

        sprite_group.setLayout(sprite_layout)
        top_layout.addWidget(sprite_group)

        # Playback controls
        play_group = QGroupBox('Playback')
        play_layout = QHBoxLayout()

        self.play_btn = QPushButton('Pause')
        self.play_btn.clicked.connect(self.toggle_play)
        play_layout.addWidget(self.play_btn)

        self.prev_btn = QPushButton('<<')
        self.prev_btn.clicked.connect(self.prev_frame)
        play_layout.addWidget(self.prev_btn)

        self.frame_slider = QSlider(Qt.Orientation.Horizontal)
        self.frame_slider.valueChanged.connect(self.jump_to_frame)
        play_layout.addWidget(self.frame_slider)

        self.next_btn = QPushButton('>>')
        self.next_btn.clicked.connect(self.next_frame)
        play_layout.addWidget(self.next_btn)

        self.fps_spin = QSpinBox()
        self.fps_spin.setRange(1, 60)
        self.fps_spin.setValue(10)
        self.fps_spin.valueChanged.connect(self.fps_changed)
        self.fps_spin.setSuffix(' fps')
        play_layout.addWidget(self.fps_spin)

        play_group.setLayout(play_layout)
        top_layout.addWidget(play_group)

        # Magnification control
        mag_group = QGroupBox('Magnification')
        mag_layout = QHBoxLayout()

        self.mag_slider = QSlider(Qt.Orientation.Horizontal)
        self.mag_slider.setRange(2, 30)
        self.mag_slider.setValue(10)
        self.mag_slider.valueChanged.connect(self.mag_changed)
        mag_layout.addWidget(self.mag_slider)

        self.mag_label = QLabel('10x')
        mag_layout.addWidget(self.mag_label)

        mag_group.setLayout(mag_layout)
        top_layout.addWidget(mag_group)

        # Scaling mode control
        scale_group = QGroupBox('Scaling')
        scale_layout = QHBoxLayout()

        self.scale_combo = QComboBox()
        for mode_name in TRANSFORM_MODES.keys():
            self.scale_combo.addItem(mode_name)
        self.scale_combo.currentTextChanged.connect(self.scale_changed)
        scale_layout.addWidget(self.scale_combo)

        scale_group.setLayout(scale_layout)
        top_layout.addWidget(scale_group)

        main_layout.addLayout(top_layout)

       # Main display area with animated cross-hatch background
        self._display_container = QWidget()
        self._display_container.setAutoFillBackground(False)
        display_layout = QHBoxLayout(self._display_container)
        display_layout.setContentsMargins(0, 0, 0, 0)
        display_layout.setSpacing(8 * self.magnification)  # Gap = half GIF width at current zoom
        
        # Create background widget for display area only
        self.background = BackgroundWidget(self._display_container)
        self.background.lower()
        # Install event filter to size background when container is shown/resized
        self._display_container.installEventFilter(self)
        
        # Left: Reconstructed animation
        left_area = QScrollArea()
        left_area.setWidgetResizable(True)
        left_area.setStyleSheet('background: transparent; border: none;')
        left_area.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.reconstructed_label = QLabel('Reconstructed')
        self.reconstructed_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.reconstructed_label.setStyleSheet('color: gray; font-size: 14px;')
        left_area.setWidget(self.reconstructed_label)
        display_layout.addWidget(left_area, 1)

        # Right: Source GIF
        right_area = QScrollArea()
        right_area.setWidgetResizable(True)
        right_area.setStyleSheet('background: transparent; border: none;')
        right_area.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.source_label = QLabel('Source GIF')
        self.source_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.source_label.setStyleSheet('color: gray; font-size: 14px;')
        right_area.setWidget(self.source_label)
        display_layout.addWidget(right_area, 1)
        
        main_layout.addWidget(self._display_container)

        # Status bar
        self.status_bar = self.statusBar()
        self.status_bar.showMessage('Ready')

        # Global keyboard shortcuts
        self.play_pause_shortcut = QShortcut(QKeySequence(Qt.Key.Key_Space), self)
        self.play_pause_shortcut.activated.connect(self.toggle_play)
        
        self.prev_sprite_shortcut = QShortcut(QKeySequence(Qt.Key.Key_Left), self)
        self.prev_sprite_shortcut.activated.connect(self.prev_sprite)
        self.next_sprite_shortcut = QShortcut(QKeySequence(Qt.Key.Key_Right), self)
        self.next_sprite_shortcut.activated.connect(self.next_sprite)
        
        self.prev_frame_shortcut = QShortcut(QKeySequence(Qt.Key.Key_PageUp), self)
        self.prev_frame_shortcut.activated.connect(self.prev_frame)
        self.next_frame_shortcut = QShortcut(QKeySequence(Qt.Key.Key_PageDown), self)
        self.next_frame_shortcut.activated.connect(self.next_frame)
        
        self.zoom_in_shortcut = QShortcut(QKeySequence(Qt.Key.Key_Plus), self)
        self.zoom_in_shortcut.activated.connect(self._zoom_in)
        self.zoom_in_shortcut2 = QShortcut(QKeySequence(Qt.Key.Key_Equal), self)
        self.zoom_in_shortcut2.activated.connect(self._zoom_in)
        
        self.zoom_out_shortcut = QShortcut(QKeySequence(Qt.Key.Key_Minus), self)
        self.zoom_out_shortcut.activated.connect(self._zoom_out)
        
        for i in range(1, 10):
            key = Qt.Key.Key_1 + (i - 1)
            shortcut = QShortcut(QKeySequence(key), self)
            shortcut.activated.connect(lambda idx=i-1: self.sprite_combo.setCurrentIndex(idx))

    def load_sprite(self, idx):
        """Load a sprite and its source GIF."""
        if idx < 0 or idx >= len(self.sprites):
            return

        self.current_sprite_idx = idx
        sprite = self.sprites[idx]
        
        # Update sprite combo box (block signals to avoid recursion)
        self.sprite_combo.blockSignals(True)
        self.sprite_combo.clear()
        for i, s in enumerate(self.sprites):
            self.sprite_combo.addItem(os.path.basename(s['path']).replace('.h', ''))
        self.sprite_combo.setCurrentIndex(idx)
        self.sprite_combo.blockSignals(False)
        
        self.current_frame = 0
        self.frame_slider.setMaximum(max(0, sprite['frames'] - 1))

        # Decompress and cache
        palette, frames = decompress_sprite(sprite)

        if palette and frames:
            self._cached_palette = palette
            self._cached_frames = frames

            # Display reconstructed frame with current magnification and scaling
            pixmap = pixels_to_image(frames[0], palette, 16 * self.magnification, self.transform_mode)
            self.reconstructed_label.setPixmap(pixmap)
            self.reconstructed_label.setText('')

            # Display source GIF if it exists
            gif_path = sprite['path'].replace('.h', '.gif')
            if os.path.exists(gif_path):
                self._show_gif(gif_path)
            else:
                self.source_label.setText('No source GIF found')
                self.source_label.setPixmap(QPixmap())

            self.status_bar.showMessage(
                f'{sprite["filename"]} | {sprite["frames"]} frames | '
                f'{sprite["datasize"]} bytes compressed | {len(palette)} colors'
            )
        else:
            self._cached_palette = None
            self._cached_frames = None
            self.reconstructed_label.setText('Failed to decompress')
            self.source_label.setText('')
            self.source_label.setPixmap(QPixmap())
            self.status_bar.showMessage('Decompression failed')

    def _show_gif(self, gif_path):
        """Display a GIF frame with same magnification as reconstructed."""
        try:
            gif = Image.open(gif_path)
            gif.seek(self.current_frame)
            # Convert to RGBA to preserve transparency
            if gif.mode not in ('RGBA',):
                rgba = gif.convert('RGBA')
            else:
                rgba = gif

            # Scale to match reconstructed size (16 * magnification)
            target_size = 16 * self.magnification
            width, height = rgba.size
            scale = target_size / max(width, height)
            new_size = (int(width * scale), int(height * scale))
            
            # Use appropriate resampling based on transform mode
            if self.transform_mode == Qt.TransformationMode.FastTransformation:
                resample = Image.Resampling.NEAREST
            else:
                resample = Image.Resampling.BICUBIC
            
            rgba = rgba.resize(new_size, resample)

            # Convert to QPixmap with alpha channel
            # Format_RGBA8888 stores bytes as R,G,B,A matching PIL's tobytes() output
            data = rgba.tobytes()
            qimg = QImage(data, rgba.width, rgba.height, QImage.Format.Format_RGBA8888)
            pixmap = QPixmap.fromImage(qimg)
            self.source_label.setPixmap(pixmap)
            self.source_label.setText('')
        except Exception as e:
            self.source_label.setText(f'Error loading GIF: {e}')
            self.source_label.setPixmap(QPixmap())

    def sprite_changed(self, idx):
        """Handle sprite selection change."""
        if self.playing:
            self.toggle_play()
        self.load_sprite(idx)
        # Restart playback
        self.playing = True
        self.play_btn.setText('Pause')
        self.timer.start(int(1000 / self.fps))

    def toggle_play(self):
        """Toggle playback."""
        self.playing = not self.playing
        if self.playing:
            self.play_btn.setText('Pause')
            self.fps = self.fps_spin.value()
            self.timer.start(int(1000 / self.fps))
        else:
            self.play_btn.setText('Play')
            self.timer.stop()

    def next_frame(self):
        """Advance to next frame."""
        sprite = self.sprites[self.current_sprite_idx]
        self.current_frame = (self.current_frame + 1) % sprite['frames']
        self.frame_slider.setValue(self.current_frame)
        self.show_current_frame()

    def prev_frame(self):
        """Go to previous frame."""
        sprite = self.sprites[self.current_sprite_idx]
        self.current_frame = (self.current_frame - 1) % sprite['frames']
        self.frame_slider.setValue(self.current_frame)
        self.show_current_frame()

    def next_sprite(self):
        """Go to next sprite/animation."""
        if len(self.sprites) <= 1:
            return
        new_idx = (self.current_sprite_idx + 1) % len(self.sprites)
        self.sprite_combo.setCurrentIndex(new_idx)

    def prev_sprite(self):
        """Go to previous sprite/animation."""
        if len(self.sprites) <= 1:
            return
        new_idx = (self.current_sprite_idx - 1) % len(self.sprites)
        self.sprite_combo.setCurrentIndex(new_idx)

    def jump_to_frame(self, frame_idx):
        """Jump to a specific frame."""
        self.current_frame = frame_idx
        self.show_current_frame()

    def show_current_frame(self):
        """Display the current frame."""
        palette = self._cached_palette
        frames = self._cached_frames

        if palette and frames and self.current_frame < len(frames):
            pixmap = pixels_to_image(
                frames[self.current_frame], 
                palette, 
                16 * self.magnification, 
                self.transform_mode
            )
            self.reconstructed_label.setPixmap(pixmap)
            self.reconstructed_label.setText('')

        # Update source GIF frame
        sprite = self.sprites[self.current_sprite_idx]
        gif_path = sprite['path'].replace('.h', '.gif')
        if os.path.exists(gif_path):
            self._show_gif(gif_path)

    def fps_changed(self, fps):
        """Handle FPS change."""
        if self.playing:
            self.timer.start(int(1000 / fps))

    def mag_changed(self, mag):
        """Handle magnification change."""
        self.magnification = mag
        self.mag_label.setText(f'{mag}x')
        # Update gap to maintain half-GIF-width spacing
        self._display_container.layout().setSpacing(8 * self.magnification)
        # Refresh current display
        if self.sprites:
            self.show_current_frame()

    def _zoom_in(self):
        """Zoom in by 1."""
        self.mag_slider.setValue(min(30, self.magnification + 1))

    def _zoom_out(self):
        """Zoom out by 1."""
        self.mag_slider.setValue(max(2, self.magnification - 1))

    def scale_changed(self, mode_name):
        """Handle scaling mode change."""
        self.transform_mode = TRANSFORM_MODES[mode_name]
        # Refresh current display
        if self.sprites:
            self.show_current_frame()

    def keyPressEvent(self, event):
        """Handle keyboard shortcuts."""
        modifiers = event.modifiers()
        
        # Ctrl+Left/Right for frame navigation (QShortcut doesn't handle modifiers cleanly)
        if event.key() == Qt.Key.Key_Left and modifiers & Qt.KeyboardModifier.ControlModifier:
            self.prev_frame()
        elif event.key() == Qt.Key.Key_Right and modifiers & Qt.KeyboardModifier.ControlModifier:
            self.next_frame()
        else:
            super().keyPressEvent(event)

    def wheelEvent(self, event):
        """Handle mouse wheel for zoom."""
        if event.angleDelta().y() > 0:
            self.mag_slider.setValue(min(30, self.magnification + 1))
        else:
            self.mag_slider.setValue(max(2, self.magnification - 1))

    def eventFilter(self, obj, event):
        """Event filter to size background when display_container is shown."""
        if obj is getattr(self, '_display_container', None):
            if event.type() == QEvent.Type.Show:
                parent = cast(QWidgetType, self.background.parent())
                if parent:
                    self.background.setGeometry(parent.rect())
                    self.background.update()
        return super().eventFilter(obj, event)

    def resizeEvent(self, event):
        """Handle window resize to keep background in sync."""
        super().resizeEvent(event)
        if hasattr(self, 'background'):
            parent = cast(QWidgetType, self.background.parent())
            if parent:
                self.background.setGeometry(parent.rect())
                self.background.update()


def main():
    parser = argparse.ArgumentParser(description='View heatshrink-compressed sprite animations')
    parser.add_argument(
        'headers', nargs='*',
        help='C header files to load (default: all GIF/*.h)'
    )
    args = parser.parse_args()

    app = QApplication(sys.argv)
    app.setStyle('Fusion')

    window = SpriteViewer(args.headers)
    window.show()

    sys.exit(app.exec())


if __name__ == '__main__':
    main()
